"""baseline schema (full metadata)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-29

Pragmatic baseline: creates the entire current schema from the SQLAlchemy
metadata (checkfirst, so it is a no-op on tables that already exist from an
earlier create_all dev run). Subsequent schema changes get their own
autogenerated revisions on top of this one.
"""
from alembic import op

from app.core.database import Base
import app.models  # noqa: F401  (register all tables)

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind(), checkfirst=True)


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
